Sprint2
ClevertecFrontendLab/sprint2-Marina2609 pull request #1
Opened 2023-02-08 11:58 UTC by Marina2609

It remains to bring beauty

2023-02-08 12:00 UTC, Rastamanby commented
#  Результаты тестов
Процент пройденных тестов: 100%.
Общее количество тестов: 10.
Количество непройденных тестов: 0.
***
**app 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Marina2609/1675857641/app%20320px.png)
***
**app 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Marina2609/1675857641/app%20768px.png)
***
**app burger-menu close 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Marina2609/1675857641/app%20burger-menu%20close%20320px.png)
***
**app burger-menu close 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Marina2609/1675857641/app%20burger-menu%20close%20768px.png)
***
**app burger-menu close click not burger-menu 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Marina2609/1675857641/app%20burger-menu%20close%20click%20not%20burger-menu%20320px.png)
***
**app burger-menu close click not burger-menu 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Marina2609/1675857641/app%20burger-menu%20close%20click%20not%20burger-menu%20768px.png)
***
**app burger-menu open 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Marina2609/1675857641/app%20burger-menu%20open%20320px.png)
***
**app burger-menu open 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Marina2609/1675857641/app%20burger-menu%20open%20768px.png)
***
**app.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Marina2609/1675857641/app.png)
***
**book-page comment collapse.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Marina2609/1675857641/book-page%20comment%20collapse.png)
***
**book-page comment expand.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Marina2609/1675857641/book-page%20comment%20expand.png)
***
**slider after 1440px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Marina2609/1675857641/slider%20after%201440px.png)
***
**slider after 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Marina2609/1675857641/slider%20after%20320px.png)
***
**slider after 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Marina2609/1675857641/slider%20after%20768px.png)
***
**slider before 1440px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Marina2609/1675857641/slider%20before%201440px.png)
***
**slider before 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Marina2609/1675857641/slider%20before%20320px.png)
***
**slider before 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Marina2609/1675857641/slider%20before%20768px.png)
***
**slider more two foto 1440px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Marina2609/1675857641/slider%20more%20two%20foto%201440px.png)
***
**slider more two foto 320px (1).png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Marina2609/1675857641/slider%20more%20two%20foto%20320px%20(1).png)
***
**slider more two foto 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Marina2609/1675857641/slider%20more%20two%20foto%20320px.png)
***
**slider more two foto 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Marina2609/1675857641/slider%20more%20two%20foto%20768px.png)
***
**slider not foto 1440px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Marina2609/1675857641/slider%20not%20foto%201440px.png)
***
**slider not foto 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Marina2609/1675857641/slider%20not%20foto%20320px.png)
***
**slider not foto 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Marina2609/1675857641/slider%20not%20foto%20768px.png)
***
**slider one foto 1440px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Marina2609/1675857641/slider%20one%20foto%201440px.png)
***
**slider one foto 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Marina2609/1675857641/slider%20one%20foto%20320px.png)
***
**slider one foto 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Marina2609/1675857641/slider%20one%20foto%20768px.png)

2023-02-08 12:16 UTC, Gaurrus requested changes
в целом перепроверь всё на соответствие дизайну

2023-02-08 12:16 UTC, Gaurrus commented on .editorconfig
> +
![image](https://user-images.githubusercontent.com/85307211/217524855-e1e649b7-b811-4cec-ae2f-623e09c63c3f.png)
320 не айс - сверься с дизайном

2023-02-09 09:00 UTC, Rastamanby commented
#  Результаты тестов
Процент пройденных тестов: 100%.
Общее количество тестов: 10.
Количество непройденных тестов: 0.
***
**app 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Marina2609/1675933237/app%20320px.png)
***
**app 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Marina2609/1675933237/app%20768px.png)
***
**app burger-menu close 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Marina2609/1675933237/app%20burger-menu%20close%20320px.png)
***
**app burger-menu close 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Marina2609/1675933237/app%20burger-menu%20close%20768px.png)
***
**app burger-menu close click not burger-menu 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Marina2609/1675933237/app%20burger-menu%20close%20click%20not%20burger-menu%20320px.png)
***
**app burger-menu close click not burger-menu 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Marina2609/1675933237/app%20burger-menu%20close%20click%20not%20burger-menu%20768px.png)
***
**app burger-menu open 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Marina2609/1675933237/app%20burger-menu%20open%20320px.png)
***
**app burger-menu open 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Marina2609/1675933237/app%20burger-menu%20open%20768px.png)
***
**app.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Marina2609/1675933237/app.png)
***
**book-page comment collapse.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Marina2609/1675933237/book-page%20comment%20collapse.png)
***
**book-page comment expand.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Marina2609/1675933237/book-page%20comment%20expand.png)
***
**slider after 1440px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Marina2609/1675933237/slider%20after%201440px.png)
***
**slider after 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Marina2609/1675933237/slider%20after%20320px.png)
***
**slider after 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Marina2609/1675933237/slider%20after%20768px.png)
***
**slider before 1440px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Marina2609/1675933237/slider%20before%201440px.png)
***
**slider before 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Marina2609/1675933237/slider%20before%20320px.png)
***
**slider before 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Marina2609/1675933237/slider%20before%20768px.png)
***
**slider more two foto 1440px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Marina2609/1675933237/slider%20more%20two%20foto%201440px.png)
***
**slider more two foto 320px (1).png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Marina2609/1675933237/slider%20more%20two%20foto%20320px%20(1).png)
***
**slider more two foto 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Marina2609/1675933237/slider%20more%20two%20foto%20320px.png)
***
**slider more two foto 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Marina2609/1675933237/slider%20more%20two%20foto%20768px.png)
***
**slider not foto 1440px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Marina2609/1675933237/slider%20not%20foto%201440px.png)
***
**slider not foto 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Marina2609/1675933237/slider%20not%20foto%20320px.png)
***
**slider not foto 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Marina2609/1675933237/slider%20not%20foto%20768px.png)
***
**slider one foto 1440px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Marina2609/1675933237/slider%20one%20foto%201440px.png)
***
**slider one foto 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Marina2609/1675933237/slider%20one%20foto%20320px.png)
***
**slider one foto 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Marina2609/1675933237/slider%20one%20foto%20768px.png)

2023-02-09 09:47 UTC, Gaurrus requested changes

2023-02-09 09:47 UTC, Gaurrus commented on .editorconfig
> +charset = utf-8
![image](https://user-images.githubusercontent.com/85307211/217776844-2f8c6a19-b191-4de2-878f-d9dcec7c61ce.png)
цввета и размеры выделенного элемента пагинации не по дизайну

2023-02-09 09:47 UTC, Gaurrus commented on .editorconfig
> +trim_trailing_whitespace = true
![image](https://user-images.githubusercontent.com/85307211/217777305-918c0ccb-d679-4b6a-ba16-6795c2a28f67.png)
отсутствует выделение активного слайда

2023-02-09 10:45 UTC, Rastamanby commented
#  Результаты тестов
Процент пройденных тестов: 100%.
Общее количество тестов: 10.
Количество непройденных тестов: 0.
***
**app 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Marina2609/1675939555/app%20320px.png)
***
**app 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Marina2609/1675939555/app%20768px.png)
***
**app burger-menu close 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Marina2609/1675939555/app%20burger-menu%20close%20320px.png)
***
**app burger-menu close 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Marina2609/1675939555/app%20burger-menu%20close%20768px.png)
***
**app burger-menu close click not burger-menu 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Marina2609/1675939555/app%20burger-menu%20close%20click%20not%20burger-menu%20320px.png)
***
**app burger-menu close click not burger-menu 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Marina2609/1675939555/app%20burger-menu%20close%20click%20not%20burger-menu%20768px.png)
***
**app burger-menu open 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Marina2609/1675939555/app%20burger-menu%20open%20320px.png)
***
**app burger-menu open 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Marina2609/1675939555/app%20burger-menu%20open%20768px.png)
***
**app.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Marina2609/1675939555/app.png)
***
**book-page comment collapse.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Marina2609/1675939555/book-page%20comment%20collapse.png)
***
**book-page comment expand.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Marina2609/1675939555/book-page%20comment%20expand.png)
***
**slider after 1440px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Marina2609/1675939555/slider%20after%201440px.png)
***
**slider after 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Marina2609/1675939555/slider%20after%20320px.png)
***
**slider after 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Marina2609/1675939555/slider%20after%20768px.png)
***
**slider before 1440px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Marina2609/1675939555/slider%20before%201440px.png)
***
**slider before 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Marina2609/1675939555/slider%20before%20320px.png)
***
**slider before 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Marina2609/1675939555/slider%20before%20768px.png)
***
**slider more two foto 1440px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Marina2609/1675939555/slider%20more%20two%20foto%201440px.png)
***
**slider more two foto 320px (1).png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Marina2609/1675939555/slider%20more%20two%20foto%20320px%20(1).png)
***
**slider more two foto 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Marina2609/1675939555/slider%20more%20two%20foto%20320px.png)
***
**slider more two foto 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Marina2609/1675939555/slider%20more%20two%20foto%20768px.png)
***
**slider not foto 1440px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Marina2609/1675939555/slider%20not%20foto%201440px.png)
***
**slider not foto 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Marina2609/1675939555/slider%20not%20foto%20320px.png)
***
**slider not foto 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Marina2609/1675939555/slider%20not%20foto%20768px.png)
***
**slider one foto 1440px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Marina2609/1675939555/slider%20one%20foto%201440px.png)
***
**slider one foto 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Marina2609/1675939555/slider%20one%20foto%20320px.png)
***
**slider one foto 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Marina2609/1675939555/slider%20one%20foto%20768px.png)

2023-02-09 10:49 UTC, Gaurrus approved these changes

2023-02-09 10:51 UTC, merged